### ISSUE TITLE
Error: Cannot find module 'word-extractor'

### ISSUE THREAD

**Issue by CreativeWolf** [morungos/node-word-extractor#5]
Hi,

Tried running the example given and it throws an error 

> Error: Cannot find module 'word-extractor'

```var WordExtractor = require("word-extractor");
var extractor = new WordExtractor();
var doc = extractor.extract("file.doc")
var body = doc.getBody();```

> Error: Cannot find module 'word-extractor'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\test\Desktop\text\3.js:1:83)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

Any help please?

**Comment by morungos** [comment]
Oh that was embarrassing. The sources were present, but not the usable binaries. I've updated the module and bumped to a version 0.1.3 which also includes a dependency fix.
